pipeline {
	agent any
	stages {
		stage('Checkout') {
			steps {
				echo 'Checking out code'
				checkout scm
			}
		}
		stage('Both Build and Test in Docker') { 
			agent {
				docker {
					image 'python:3.11.0-slim-buster'
					reuseNode true
				}
			}
			stages{
				stage('Build'){
					steps {
						sh 'apt update && apt install libmariadb-dev build-essential -y'
						sh 'pip install --no-cache-dir -r src/requirements.txt' 
						sh 'pip install pytest'  
					}
				}
				stage('Feature Test') {
					steps {
						sh 'pytest jenkins/scripts/loginTest.py'
					}
				}
			}
		}
		stage('OWASP Dependency-Check'){
			steps {
				dependencyCheck additionalArguments: '--scan "src/" --format HTML --format XML', odcInstallation: '3x03_FMS'
			}
		}
    }
	post {
		success {
			dependencyCheckPublisher pattern: 'dependency-check-report.xml'
		}
	}
}
