pipeline {
	agent {
		docker {
			image 'python:3.11.0-slim-buster'
		}
	}
	stages {
		stage('Checkout') {
			steps {
				echo 'Checking out code'
				checkout scm
			}
		}
        stage('Build') { 
            steps {
				sh 'apt update && apt install libmariadb-dev build-essential -y'
                sh 'pip install --no-cache-dir -r src/requirements.txt' 
				sh 'pip install pytest'
            }
        }
		stage('OWASP Dependency-Check'){
			agent any
			steps {
				dependencyCheck additionalArguments: '--scan "src/" --format HTML --format XML', odcInstallation: '3x03_FMS'
			}
		}
		stage('Base Feature Test'){
			steps {
				sh 'pytest jenkins/scripts/loginTest.py'
			}
		}
    }
	post {
		success {
			dependencyCheckPublisher pattern: 'dependency-check-report.xml'
		}
	}
}